name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '0 0 * * *' # every night at 0 am UTC

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: $
          expire-in: 2days # Set this to 0 to delete all artifacts